name: Auto Tag on Version Change

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      changed: ${{ steps.version_changed.outputs.changed }}
      valid: ${{ steps.validate_semver.outputs.valid }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Get current version
        id: current_version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Get previous version
        id: previous_version
        run: |
          git checkout HEAD~1
          PREVIOUS_VERSION=$(node -p "require('./package.json').version" 2>/dev/null || echo "0.0.0")
          git checkout -
          echo "version=$PREVIOUS_VERSION" >> $GITHUB_OUTPUT

      - name: Check if version changed
        id: version_changed
        run: |
          if [ "${{ steps.current_version.outputs.version }}" != "${{ steps.previous_version.outputs.version }}" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Validate semver
        if: steps.version_changed.outputs.changed == 'true'
        id: validate_semver
        run: |
          VERSION="${{ steps.current_version.outputs.version }}"
          if [[ $VERSION =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$ ]]; then
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "valid=false" >> $GITHUB_OUTPUT
            echo "::error::Version $VERSION is not a valid semver"
            exit 1
          fi

      - name: Create tag
        if: steps.version_changed.outputs.changed == 'true' && steps.validate_semver.outputs.valid == 'true'
        run: |
          VERSION="v${{ steps.current_version.outputs.version }}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "$VERSION" -m "Release $VERSION"
          git push origin "$VERSION"

  publish:
    runs-on: ubuntu-latest
    needs: auto-tag
    if: needs.auto-tag.result == 'success' && needs.auto-tag.outputs.changed == 'true' && needs.auto-tag.outputs.valid == 'true'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: '22'

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build package
        run: bun run build

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
